name: Build DDC

on:
  workflow_dispatch:
    inputs:
      tag_name:
        type: string
        required: true

jobs:
  windows-build:
    name: Windows x64
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2  

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: "1.20.14"

    - name: Build
      run: ./build/build-windows.ps1
      shell: pwsh

    - name: Upload
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{inputs.tag_name}}
        make_latest: true
        files: |
          Deeeep.io-Desktop-Client-Windows.zip

  macos-x64:
    name: MacOS x64
    runs-on: macos-12
    steps: 
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: "1.20.14"

    - name: Build
      run: ./build/build-macos-x64.sh
      shell: bash
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-x64
        path: ddc_amd64

  macos-build:
    name: MacOS arm64
    runs-on: macos-14
    needs: [macos-x64]
    steps:
    - name: Checkout
      uses: actions/checkout@v2  

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: macos-x64
        path: .

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: "1.20.14"

    - name: Build
      run: |
        ./build/build-macos-arm64.sh
        ./build/build-macos-universal.sh
      shell: bash
  
    - name: Upload
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{inputs.tag_name}}
        make_latest: true
        files: |
          Deeeep.io-Desktop-Client-MacOS.zip

  linux-build:
    name: Linux x64
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2  

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: "1.20.14"

    - name: Build
      run: ./build/build-linux.sh
      shell: bash

    - name: Upload
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{inputs.tag_name}}
        make_latest: true
        files: |
          Deeeep.io-Desktop-Client-Linux.tar.gz
          