name: Build DDC

on:
  workflow_dispatch:
    inputs:
      tag_name:
        type: string
        required: true

jobs:
  windows-build:
      name: Windows x64
      runs-on: windows-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2  

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20.3"

      - name: Build
        run: ./build/build-windows.ps1
        shell: pwsh

      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{inputs.tag_name}}
          make_latest: true
          files: |
            Deeeep.io-Desktop-Client-Windows.zip

  macos-build:
      name: Mac OS Universal
      runs-on: macos-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2  

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20.3"

      - name: Build
        run: ./build/build-macos.sh
        shell: bash
  
      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{inputs.tag_name}}
          make_latest: true
          files: |
            Deeeep.io-Desktop-Client-MacOS.zip

  linux-build:
    name: Linux x64
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2  

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: "1.20.3"

    - name: Build
      run: ./build/build-linux.sh
      shell: bash

    - name: Upload
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{inputs.tag_name}}
        make_latest: true
        files: |
          Deeeep.io-Desktop-Client-Linux.tar.gz
          